<?xml version="1.0"?>
<package format="3">
  <name>rov_pipe_tracker</name>
  <version>0.0.1</version>
  <description>Track underwater pipes from segmentation masks and send MAVLink manual control.</description>
  <maintainer email="xylin@example.com">xylin</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>rclcpp_components</depend>
  <depend>rcl_interfaces</depend>
  <depend>sensor_msgs</depend>
  <depend>ai_msgs</depend>
  <depend>std_msgs</depend>
  <depend>std_srvs</depend>
  <exec_depend>rclpy</exec_depend>

  <build_depend>opencv</build_depend>
  <exec_depend>opencv</exec_depend>

  <exec_depend>camera_driver</exec_depend>
  <exec_depend>dehaze</exec_depend>
  <exec_depend>dehaze_segmentation</exec_depend>
  <exec_depend>dnn_node_example</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
